name: Continious delivery to Docker hub
on:
  push:
    branches: [ releases/** ]
jobs:
  push_to_registry:
    env:
      REPO_NAME: sacation/letschess-gameservice
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/releases/})"
        id: extract_branch
        
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REPO_NAME }}:${{ steps.extract_branch.outputs.branch }}
      - name: Push to Docker Hub latest tag
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REPO_NAME }}:latest